// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxgnwvklffvibwtwgysk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Z253dmtsZmZ2aWJ3dHdneXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzQzNzgsImV4cCI6MjA2ODkxMDM3OH0.h1VXM8RyWEKTWs-ZV5oQ0GLsRhJbNTlXC1pA772oNdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});